# Generated by Django 3.0.5 on 2020-04-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='publish_time',
            field=models.DateField(max_length=200),
        ),
    ]
