# Generated by Django 3.0.5 on 2020-04-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_auto_20200411_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='coevidence',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='paper',
            name='full_text_file',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='paper',
            name='has_pdf_parse',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='paper',
            name='has_pmc_xml_parse',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='paper',
            name='publish_date',
            field=models.DateField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='paper',
            name='publish_time',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
