# Generated by Django 3.0.5 on 2020-04-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0007_auto_20200412_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='who',
        ),
        migrations.AlterField(
            model_name='paper',
            name='coevidence',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='WHO #Covidence'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='microsoft_pid',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Microsoft Academic Paper ID'),
        ),
    ]
